# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c5522c366a54713f298877ebe087a288"
name = "SyncBridge"
handle = "syncbridge"
application_url = "https://shopify-app-template-remix-five.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [
  "https://shopify-app-template-remix-five.vercel.app/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
